name: UI tests

on:
  push:
    branches:
      - main
    pull_request:
      - main


jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v7